### ISSUE TITLE
The final structure used for 6sba

### ISSUE THREAD

**Issue by amin-sagar** [schrodinger/protein-fep-benchmark#1] opened 2024-09-16 15:37 UTC
Hello.
This is awesome work and thanks for sharing the data.
I would like to test other FEP approaches like perses on the 6sba dataset.
I have a couple of questions/requests.

1. The available maestro files don't seem to have the bond between E10 and K25 for cyclization. Was this bond created for FEP calculations?
2. Was the P1L residue kept as such or was it mutated to cysteine?

It would be really great if you can also share the final structure which was used for FEP calculations for best comparison with other approaches.

Best,
Amin.

**Comment by jaredsampson** [comment] 2024-09-19 16:18
Hi Amin - Thank you for the kind words about the paper, and for taking the time to ask these questions.

It turns out I uploaded the wrong structure file for 6SBA (`models/6SBA_prepared.mae`), which was not used in the FEP calculations.  I'll be uploading the correct file, `models/6SBA_prepared_cyclized.mae`, which I have confirmed was used for the FEP.  This model contains the covalent bond between E10 and K25, which you noticed was missing in the incorrect version.  Many thanks for pointing out the error!

As for the P1L residue: we prepared this cyclized model from a pre-publication version of the mTEAD/VGL4 mimetic peptide structure, and at the time there was some uncertainty about whether the fatty acid should be modeled as covalently linked to the Cys360.  I didn't notice that the deposited structure contained the covalent linkage, so in all the calculations from this paper it is represented as MYR (myristic acid) and intact Cys360.  Since this part of the structure isn't involved in peptide binding, I don't expect this difference would have an appreciable effect on the FEP results, but for future studies, I would recommend using the deposited coordinates rather than the model in this repo.

I hope this answers your questions.  I'll be uploading the correct structure file shortly and closing this issue.  Best wishes with your research!

**Closed as completed** 2024-09-19 16:52 UTC
